import { ARTISTS_DATA, COLLECTIONS_DATA, NTFS_DATA } from './api';
import { BANNER_INFO_DATA, HEADER_LINKS, HOW_IT_WORKS_ITEMS_DATA, SOCIAL_LINKS } from './data';
import { PROJECT_NAME } from './main';
import { PATHS } from './paths';

export {
    ARTISTS_DATA,
    COLLECTIONS_DATA,
    NTFS_DATA,
    BANNER_INFO_DATA,
    HEADER_LINKS,
    HOW_IT_WORKS_ITEMS_DATA,
    SOCIAL_LINKS,
    PROJECT_NAME,
    PATHS,
};
