import {
    CLIENTS_DATA,
    HEADER_LINKS_DATA,
    HEADER_USER_LINKS_DATA,
    HERO_INFO_DATA,
    HOW_IT_WORKS_ITEMS_DATA,
    NEW_EVENT_DATA,
    SOCIAL_LINKS_DATA,
    USER_DATA,
    WALLET_OPTIONS_DATA,
} from './data';
import { API, PROJECT_NAME } from './main';
import { PATHS } from './paths';

export {
    CLIENTS_DATA,
    HEADER_LINKS_DATA,
    HEADER_USER_LINKS_DATA,
    HERO_INFO_DATA,
    HOW_IT_WORKS_ITEMS_DATA,
    NEW_EVENT_DATA,
    SOCIAL_LINKS_DATA,
    USER_DATA,
    WALLET_OPTIONS_DATA,
    API,
    PROJECT_NAME,
    PATHS,
};
