import { BANNER_INFO_DATA, HEADER_LINKS, HOW_IT_WORKS_ITEMS_DATA, SOCIAL_LINKS } from './data';
import { API, PROJECT_NAME } from './main';
import { PATHS } from './paths';

export { BANNER_INFO_DATA, HEADER_LINKS, HOW_IT_WORKS_ITEMS_DATA, SOCIAL_LINKS, API, PROJECT_NAME, PATHS };
